### PR TITLE
Throws an error when signing with a locked keypair

### LINKED ISSUE #576: Throw an error when the keypair is locked
Currently the "locked" keypair has a secret key of zero:

https://github.com/polkadot-js/common/blob/697a452ba6be77b747dbf745bef790313ded8285/packages/keyring/src/pair/index.ts#L136-L138

`sign()` will return an invalid signature if a developer forgets to check `.isLocked` before signing:

https://github.com/polkadot-js/common/blob/697a452ba6be77b747dbf745bef790313ded8285/packages/keyring/src/pair/index.ts#L142-L143

 This is confusing to new developers. It's better to raise an error instead of returning a wrong signature here.

### PR DESCRIPTION
**Pull request by h4x3rotab**
Fixes #576

### CODE REVIEW

File: packages/keyring/src/pair/index.ts [hunk 1]
```diff
@@ -124,8 +128,9 @@ export default function createPair ({ toSS58, type }: Setup, { publicKey, secret
       }
     },
     derive: (suri: string, meta?: KeyringPair$Meta): KeyringPair => {
-      assert(secretKey, 'Cannot derive on a locked keypair');
-
+      if (!secretKey || isLocked(secretKey)) {
```
Comment (jacogr) [inline packages/keyring/src/pair/index.ts:131]:
```suggestion
      if (isLocked(secretKey)) {
```

`isLocked` already checks for `!secretKey`

File: packages/keyring/src/pair/index.ts [hunk 2]
```diff
@@ -62,6 +62,10 @@ function verify (type: KeypairType, message: Uint8Array, signature: Uint8Array,
     : naclVerify(message, signature, publicKey);
 }
 
+function isLocked (secretKey?: Uint8Array): boolean {
```
Comment (jacogr) [inline packages/keyring/src/pair/index.ts:65]:
```suggestion
function isLocked (secretKey?: Uint8Array): secretKey is Uint8Array {
```

If passing, it will be seen as a valid u8a

File: packages/keyring/src/pair/index.ts [hunk 3]
```diff
@@ -139,8 +144,12 @@ export default function createPair ({ toSS58, type }: Setup, { publicKey, secret
     setMeta: (additional: KeyringPair$Meta): void => {
       meta = { ...meta, ...additional };
     },
-    sign: (message: Uint8Array, options?: SignOptions): Uint8Array =>
-      sign(type, message, { publicKey, secretKey }, options),
+    sign: (message: Uint8Array, options?: SignOptions): Uint8Array => {
+      if (isLocked(secretKey)) {
+        throw new Error('Cannot sign with a locked key pair');
+      }
```
Comment (jacogr) [inline packages/keyring/src/pair/index.ts:150]:
```suggestion
      assert(!isLocked(secretKey), 'Cannot sign with a locked key pair');
      
```

File: packages/keyring/src/pair/index.ts [hunk 4]
```diff
@@ -124,8 +128,9 @@ export default function createPair ({ toSS58, type }: Setup, { publicKey, secret
       }
     },
     derive: (suri: string, meta?: KeyringPair$Meta): KeyringPair => {
-      assert(secretKey, 'Cannot derive on a locked keypair');
-
+      if (!secretKey || isLocked(secretKey)) {
+        throw new Error('Cannot derive on a locked keypair');
+      }
```
Comment (jacogr) [inline packages/keyring/src/pair/index.ts:133]:
```suggestion
      assert(!isLocked(secretKey), 'Cannot derive on a locked keypair');
      
```

isLocked already checks for !secretKey

File: packages/keyring/src/pair/index.ts [hunk 5]
```diff
@@ -6,7 +6,7 @@ import { Keypair, KeypairType } from '@polkadot/util-crypto/types';
 import { KeyringPair, KeyringPair$Json, KeyringPair$Meta, SignOptions } from '../types';
 import { PairInfo } from './types';
 
-import { u8aConcat, assert } from '@polkadot/util';
+import { u8aConcat } from '@polkadot/util';
```
Comment (jacogr) [inline packages/keyring/src/pair/index.ts:9]:
```suggestion
import { assert, u8aConcat } from '@polkadot/util';
```

Includes `assert` used below.

File: packages/keyring/src/pair/index.ts (hunk 2 above)
Comment (h4x3rotab) [reply packages/keyring/src/pair/index.ts:65]: Done. Good suggestion

File: packages/keyring/src/pair/index.ts (hunk 3 above)
Comment (h4x3rotab) [reply packages/keyring/src/pair/index.ts:150]: Done

File: packages/keyring/src/pair/index.ts (hunk 4 above)
Comment (h4x3rotab) [reply packages/keyring/src/pair/index.ts:133]: Done

File: packages/keyring/src/pair/index.ts (hunk 5 above)
Comment (h4x3rotab) [reply packages/keyring/src/pair/index.ts:9]: Done

File: packages/keyring/src/pair/index.ts [hunk 6]
```diff
@@ -124,10 +128,10 @@ export default function createPair ({ toSS58, type }: Setup, { publicKey, secret
       }
     },
     derive: (suri: string, meta?: KeyringPair$Meta): KeyringPair => {
-      assert(secretKey, 'Cannot derive on a locked keypair');
+      assert(!isLocked(secretKey), 'Cannot derive on a locked keypair');
 
       const { path } = keyExtractPath(suri);
-      const derived = keyFromPath({ publicKey, secretKey: secretKey }, path, type);
+      const derived = keyFromPath({ publicKey, secretKey: secretKey! }, path, type);
```
Comment (jacogr) [inline packages/keyring/src/pair/index.ts:134]:
```suggestion
      const derived = keyFromPath({ publicKey, secretKey: secretKey }, path, type);
```

Comment (jacogr) [reply packages/keyring/src/pair/index.ts:134]: Sorry about this - the linter does complain, but since the isLocked now does it properly, we are ok and can cleanup.

Comment (h4x3rotab) [reply packages/keyring/src/pair/index.ts:134]: I hope I would know more about Typescript but the linter is still complaining. Let me do some homework :)

Comment (jacogr) [reply packages/keyring/src/pair/index.ts:134]: Grrrr... so that just says the value should not be empty. And the assert/isLocked checks for that - so should just work as expected.

Comment (h4x3rotab) [reply packages/keyring/src/pair/index.ts:134]: The linter doesn't allow `secretKey` without the not-null assertion.

Just read the doc about [type predicates](https://www.typescriptlang.org/docs/handbook/advanced-types.html#using-type-predicates). It looks like a function with a type predicate return type notation is used for narrowing down a type. And the predicates should be used in compiling time. However `isLocked` is used in runtime because it also checks the content of `secretKey`. So it sounds to me a better way is to return a boolean and add change it back to `secretKey: secretKey!`.

Comment (jacogr) [reply packages/keyring/src/pair/index.ts:134]: Something is funny here. But anyway, a warning (although it is only that way since al the `!`'s have not been cleaned - so many hours in a day).

Not going to waste your time, going to get it is since it works.

Comment (jacogr) [reply packages/keyring/src/pair/index.ts:134]: *slush* Was my bug, not yours.

So `isLocked(Uint8Array | undefined)` is true if not a valid (for us), Uint8Array. So effectively we should return "it is not a (valid) Uint8Array".

Adjusting it somewhat in my linting branch.
